title: Raghavi Rajumohan
description: >
  Passionate about uncovering data insights to drive informed business decisions and actionable strategies.
  <br><br>

    <!-- Experiences Section -->
  <strong style="font-size: 1em; display: block; margin-bottom: 5px; margin-top: 0;">Experiences:</strong>
  <div style="position: relative; max-width: 800px; margin: 20px auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">

    <!-- Experience 1 -->
    <div style="padding: 10px 0; position: relative; border-bottom: 1px solid #ddd;">
      <div style="font-weight: bold; color: #6e8cd4; font-size: 0.85em;">Jul 2024 - Present</div>
      <div style="font-weight: bold; font-size: 1.1em;">Data Metrics Analyst Intern</div>
      <div style="font-size: 0.9em;">University of California, Office of the President</div>
    </div>
  
    <!-- Experience 2 -->
    <div style="padding: 10px 0; position: relative; border-bottom: 1px solid #ddd;">
      <div style="font-weight: bold; color: #6e8cd4; font-size: 0.85em;">Jan 2024 - May 2024</div>
      <div style="font-weight: bold; font-size: 1.1em;">Data Analyst and Project Mentor</div>
      <div style="font-size: 0.9em;">UCLA Alumni Affairs</div>
    </div>

      <!-- Experience 3 -->
    <div style="padding: 10px 0; position: relative; border-bottom: 1px solid #ddd;">
      <div style="font-weight: bold; color: #6e8cd4; font-size: 0.85em;">Sep 2020 - Jul 2023</div>
      <div style="font-weight: bold; font-size: 1.1em;">Data Analysis General Manager</div>
      <div style="font-size: 0.9em;">WageIndicator Foundation Research Lab</div>
    </div>
  
    <!-- Experience 4 -->
    <div style="padding: 10px 0; position: relative;">
      <div style="font-weight: bold; color: #6e8cd4; font-size: 0.85em;">May 2021 - Jul 2022</div>
      <div style="font-weight: bold; font-size: 1.1em;">Business Development Intern</div>
      <div style="font-size: 0.9em;">TATA Electronics Pvt. Ltd.</div>
    </div>

  </div>

  <strong style="margin-top: 20px; display: block;">Connect with Me:</strong>
  <div style="display: flex; justify-content: center; gap: 20px; margin: 10px 0;">
    <a href="https://www.linkedin.com/in/raghavi-rajumohan/" style="color:#6a0dad; text-align: center; text-decoration: none;" target="_blank" rel="noopener noreferrer">
      <img src="assets/linkedin.png" alt="LinkedIn" style="width:30px;height:30px; display: block; margin: 0 auto;">
      <span style="font-size: 0.9em; display: block; margin-top: 5px;">LinkedIn</span>
    </a>
    <a href="https://github.com/RaghaviRajumohan/Rhythms-of-Data" style="color:#6a0dad; text-align: center; text-decoration: none;" target="_blank" rel="noopener noreferrer">
      <img src="assets/github.png" alt="GitHub" style="width:30px;height:30px; display: block; margin: 0 auto;">
      <span style="font-size: 0.9em; display: block; margin-top: 5px;">GitHub</span>
    </a>
  </div>
  
show_downloads: true
theme: jekyll-theme-minimal

# Optional: Add Sass compression
sass:
  style: compressed
